FROM nginx:1.19
LABEL Maintainer = "stevereg1@groom.ch"
LABEL Author = "Steve Groom"

##RUN touch /var/log/debug.log 
## && ln -sf /dev/stdout /var/log/debug.log

CMD ["nginx", "-g", "daemon off;"]
#CMD ["nginx"]
